pt:
  languageCode: pt
  languageName: Portuguese
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  # contentDir: content/i18n

# Uncomment for multilingual sites, and customize the following config.
# zh:
#   languageCode: zh
#   languageName: 简体中文
#   contentDir: content/zh
#   title: 中文标题
